import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next Öğreniyorum</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1 className={styles.title}>
        <a href='http://localhost:3000/hakkimizda'>Home!</a>
      </h1>
      {/* https://jsonplaceholder.typicode.com/posts?_limit=5 */}

      <div>
        {posts.map((post) => (
          <ul key={post.id}>
            <h3>{post.title}</h3>
              <p>{post.body}</p>
          </ul>
        ))}
      </div>
    </div>
  )
}

export const getStaticProps = async () => {
  const res = await fetch('https://jsonplaceholder.typicode.com/posts?_limit=3')
  const posts = await res.json();

  return {
    props: { posts },
  }
}
